/**
 * Server-Side Image Optimization Service.
 *
 * Processes images directly on the Node.js server using Sharp.js
 * - Creates AVIF, WebP, and optimized JPEG variants
 * - Uploads all variants to S3
 * - No AWS Lambda required.
 *
 * Created by Denisse Maldonado.
 * @version 1.0.0
 */

const sharp = require('sharp');
const FileStorageService = require('./FileStorageService');
const logger = require('../../infrastructure/logger');

class ServerImageOptimizationService extends FileStorageService {
  constructor(config = {}) {
    super(config);

    // Optimization settings
    this.enableOptimization = process.env.ENABLE_IMAGE_OPTIMIZATION !== 'false';
    this.supportedFormats = ['avif', 'webp', 'jpeg'];
    this.qualitySettings = {
      avif: { quality: 85, effort: 4 },
      webp: { quality: 90, effort: 4 },
      jpeg: { quality: 92, progressive: true, mozjpeg: true },
    };

    // Size variants
    this.sizeVariants = {
      thumb: { width: 150, height: 150, fit: 'cover' },
      mobile: { width: 400, height: 300, fit: 'inside' },
      desktop: { width: 800, height: 600, fit: 'inside' },
      original: null, // No resizing
    };
  }

  /**
   * Upload image with server-side optimization
   * Creates multiple format variants during upload.
   * @param fileBuffer
   * @param fileName
   * @param mimeType
   * @param options
   * @example
   */
  async uploadOptimizedImage(fileBuffer, fileName, mimeType, options = {}) {
    try {
      // Generate base S3 key for original
      const baseKey = this.generateS3Key(fileName, options);
      const extension = this.getFileExtension(fileName);
      const basePath = baseKey.substring(0, baseKey.lastIndexOf('.'));

      // Upload original file first
      await this.uploadFile(fileBuffer, baseKey, mimeType, options);

      const optimizedVariants = {};

      // Create AVIF variant
      try {
        const avifBuffer = await sharp(fileBuffer)
          .avif({ quality: 85, effort: 4 })
          .toBuffer();

        const avifKey = `${basePath}.avif`;
        await this.uploadFile(avifBuffer, avifKey, 'image/avif', {
          customS3Key: avifKey,
        });

        optimizedVariants.avif = {
          s3Key: avifKey,
          format: 'avif',
        };

        logger.info('Created AVIF variant', {
          originalKey: baseKey,
          avifKey,
          size: avifBuffer.length,
        });
      } catch (error) {
        logger.warn('Failed to create AVIF variant', {
          error: error.message,
          originalKey: baseKey,
        });
      }

      // Create WebP variant
      try {
        const webpBuffer = await sharp(fileBuffer)
          .webp({ quality: 90, effort: 4 })
          .toBuffer();

        const webpKey = `${basePath}.webp`;
        await this.uploadFile(webpBuffer, webpKey, 'image/webp', {
          customS3Key: webpKey,
        });

        optimizedVariants.webp = {
          s3Key: webpKey,
          format: 'webp',
        };

        logger.info('Created WebP variant', {
          originalKey: baseKey,
          webpKey,
          size: webpBuffer.length,
        });
      } catch (error) {
        logger.warn('Failed to create WebP variant', {
          error: error.message,
          originalKey: baseKey,
        });
      }

      // Create optimized JPEG if original isn't JPEG
      if (extension !== 'jpg' && extension !== 'jpeg') {
        try {
          const jpegBuffer = await sharp(fileBuffer)
            .jpeg({ quality: 92, progressive: true, mozjpeg: true })
            .toBuffer();

          const jpegKey = `${basePath}.jpg`;
          await this.uploadFile(jpegBuffer, jpegKey, 'image/jpeg', {
            customS3Key: jpegKey,
          });

          optimizedVariants.jpeg = {
            s3Key: jpegKey,
            format: 'jpeg',
          };

          logger.info('Created JPEG variant', {
            originalKey: baseKey,
            jpegKey,
            size: jpegBuffer.length,
          });
        } catch (error) {
          logger.warn('Failed to create JPEG variant', {
            error: error.message,
            originalKey: baseKey,
          });
        }
      } else {
        // Original is already JPEG
        optimizedVariants.jpeg = {
          s3Key: baseKey,
          format: 'jpeg',
        };
      }

      // Build optimization metadata structure compatible with existing code
      const optimizationMetadata = {
        formats: {},
        original: {
          s3Key: baseKey,
          format: extension,
        },
      };

      // Add format metadata
      if (optimizedVariants.avif) {
        optimizationMetadata.formats.avif = {
          url: null, // Will be generated by presigned URL
          s3Key: optimizedVariants.avif.s3Key,
        };
      }
      if (optimizedVariants.webp) {
        optimizationMetadata.formats.webp = {
          url: null,
          s3Key: optimizedVariants.webp.s3Key,
        };
      }
      if (optimizedVariants.jpeg) {
        optimizationMetadata.formats.jpeg = {
          url: null,
          s3Key: optimizedVariants.jpeg.s3Key,
        };
      }

      logger.info('Image optimization complete', {
        originalKey: baseKey,
        formats: Object.keys(optimizedVariants),
        entityPath: options.entityPath,
      });

      return {
        success: true,
        originalS3Key: baseKey,
        optimizedVariants,
        metadata: optimizationMetadata,
      };
    } catch (error) {
      logger.error('Server-side image optimization failed:', error);

      // Fallback: upload original only
      const fallbackKey = this.generateS3Key(fileName, options);
      const fallbackUpload = await this.uploadFile(fileBuffer, fallbackKey, mimeType, options);

      return {
        success: true,
        originalS3Key: fallbackUpload.s3Key,
        optimizedVariants: {},
        metadata: {
          fallback: true,
          error: error.message,
          original: {
            s3Key: fallbackUpload.s3Key,
            format: this.getFileExtension(fileName),
          },
        },
      };
    }
  }

  /**
   * Optimize an existing image record that has no optimized variants.
   * Downloads the original from S3, creates variants, and updates the record.
   * @param {Parse.Object} imageRecord - VehicleImage or TourImage Parse object.
   * @param {string} entityPath - S3 entity path (e.g., 'vehicles/abc123' or 'tours/xyz').
   * @param _entityPath
   * @returns {Promise<object>} Optimization result.
   * @example
   */
  async optimizeExistingImage(imageRecord, _entityPath = 'general') {
    const s3Key = imageRecord.get('s3Key');
    if (!s3Key) {
      throw new Error('Image record has no s3Key');
    }

    const fileBuffer = await this.downloadFile(s3Key);
    const basePath = s3Key.replace(/\.[^.]+$/, '');
    const extension = this.getFileExtension(s3Key);

    const optimizedVariants = {};

    // Create AVIF variant
    try {
      const avifBuffer = await sharp(fileBuffer).avif({ quality: 85, effort: 4 }).toBuffer();
      const avifKey = `${basePath}.avif`;
      await this.uploadFile(avifBuffer, avifKey, 'image/avif', { customS3Key: avifKey });
      optimizedVariants.avif = { s3Key: avifKey, format: 'avif' };
    } catch (error) {
      logger.warn('Background optimization: failed to create AVIF variant', {
        imageId: imageRecord.id,
        error: error.message,
      });
    }

    // Create WebP variant
    try {
      const webpBuffer = await sharp(fileBuffer).webp({ quality: 90, effort: 4 }).toBuffer();
      const webpKey = `${basePath}.webp`;
      await this.uploadFile(webpBuffer, webpKey, 'image/webp', { customS3Key: webpKey });
      optimizedVariants.webp = { s3Key: webpKey, format: 'webp' };
    } catch (error) {
      logger.warn('Background optimization: failed to create WebP variant', {
        imageId: imageRecord.id,
        error: error.message,
      });
    }

    // Create optimized JPEG if original isn't JPEG
    if (extension !== 'jpg' && extension !== 'jpeg') {
      try {
        const jpegBuffer = await sharp(fileBuffer)
          .jpeg({ quality: 92, progressive: true, mozjpeg: true })
          .toBuffer();
        const jpegKey = `${basePath}.jpg`;
        await this.uploadFile(jpegBuffer, jpegKey, 'image/jpeg', { customS3Key: jpegKey });
        optimizedVariants.jpeg = { s3Key: jpegKey, format: 'jpeg' };
      } catch (error) {
        logger.warn('Background optimization: failed to create JPEG variant', {
          imageId: imageRecord.id,
          error: error.message,
        });
      }
    } else {
      optimizedVariants.jpeg = { s3Key, format: 'jpeg' };
    }

    // Build optimization metadata
    const optimizationMetadata = {
      formats: {},
      original: { s3Key, format: extension },
      backgroundOptimized: true,
      optimizedAt: new Date().toISOString(),
    };

    if (optimizedVariants.avif) {
      optimizationMetadata.formats.avif = { s3Key: optimizedVariants.avif.s3Key };
    }
    if (optimizedVariants.webp) {
      optimizationMetadata.formats.webp = { s3Key: optimizedVariants.webp.s3Key };
    }
    if (optimizedVariants.jpeg) {
      optimizationMetadata.formats.jpeg = { s3Key: optimizedVariants.jpeg.s3Key };
    }

    // Update the image record
    imageRecord.set('optimizedVariants', optimizedVariants);
    imageRecord.set('optimizationMetadata', optimizationMetadata);
    await imageRecord.save(null, { useMasterKey: true });

    logger.info('Background optimization completed for existing image', {
      imageId: imageRecord.id,
      s3Key,
      formats: Object.keys(optimizedVariants),
    });

    return { success: true, optimizedVariants, metadata: optimizationMetadata };
  }

  /**
   * Process image into specific format and size.
   * @param buffer
   * @param format
   * @param sizeConfig
   * @example
   */
  async processImageFormat(buffer, format, sizeConfig) {
    let sharpInstance = sharp(buffer);

    // Apply size transformation
    if (sizeConfig) {
      sharpInstance = sharpInstance.resize(sizeConfig);
    }

    // Apply format-specific optimization
    switch (format) {
      case 'avif':
        return sharpInstance.avif(this.qualitySettings.avif).toBuffer();

      case 'webp':
        return sharpInstance.webp(this.qualitySettings.webp).toBuffer();

      case 'jpeg':
        return sharpInstance.jpeg(this.qualitySettings.jpeg).toBuffer();

      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Get best available image URL for client.
   * @param originalS3Key
   * @param acceptHeader
   * @param size
   * @example
   */
  async getOptimizedImageUrl(originalS3Key, acceptHeader = '') {
    try {
      // Remove extension to get base path
      const lastDot = originalS3Key.lastIndexOf('.');
      const basePath = originalS3Key.substring(0, lastDot);

      // Detect preferred format from Accept header
      const preferredFormat = this.detectPreferredFormat(acceptHeader);

      // Build the optimized key based on format
      let optimizedKey;
      if (preferredFormat === 'avif') {
        optimizedKey = `${basePath}.avif`;
      } else if (preferredFormat === 'webp') {
        optimizedKey = `${basePath}.webp`;
      } else {
        // For JPEG preference, check if we have an optimized JPEG
        const extension = this.getFileExtension(originalS3Key);
        if (extension !== 'jpg' && extension !== 'jpeg') {
          optimizedKey = `${basePath}.jpg`;
        } else {
          // Original is already JPEG
          optimizedKey = originalS3Key;
        }
      }

      // Check if optimized version exists
      const optimizedExists = await this.checkS3ObjectExists(optimizedKey);

      if (optimizedExists) {
        const url = await this.getPresignedUrl(optimizedKey);
        return {
          url,
          format: preferredFormat,
          size: 'original',
          optimized: true,
        };
      }

      // Fallback to original
      const originalUrl = await this.getPresignedUrl(originalS3Key);

      return {
        url: originalUrl,
        format: this.getFileExtension(originalS3Key),
        size: 'original',
        optimized: false,
      };
    } catch (error) {
      console.error('Error getting optimized URL:', error);

      // Final fallback
      const originalUrl = await this.getPresignedUrl(originalS3Key);
      return {
        url: originalUrl,
        format: 'original',
        size: 'original',
        optimized: false,
        error: error.message,
      };
    }
  }

  /**
   * Detect preferred image format from Accept header.
   * @param acceptHeader
   * @example
   */
  detectPreferredFormat(acceptHeader) {
    if (!acceptHeader) return 'jpeg';

    if (acceptHeader.includes('image/avif')) return 'avif';
    if (acceptHeader.includes('image/webp')) return 'webp';
    return 'jpeg';
  }

  /**
   * Check if S3 object exists.
   * @param s3Key
   * @example
   */
  async checkS3ObjectExists(s3Key) {
    try {
      const AWS = require('aws-sdk');
      const s3 = new AWS.S3();
      await s3
        .headObject({
          Bucket: process.env.S3_BUCKET,
          Key: s3Key,
        })
        .promise();
      return true;
    } catch (error) {
      if (error.code === 'NotFound') {
        return false;
      }
      throw error;
    }
  }

  /**
   * Get file extension from filename.
   * @param filename
   * @example
   */
  getFileExtension(filename) {
    return filename.split('.').pop().toLowerCase();
  }

  /**
   * Generate S3 key for file.
   * @param fileName
   * @param options
   * @example
   */
  generateS3Key(fileName, options = {}) {
    const prefix = process.env.S3_PREFIX || '';
    const entityPath = options.entityPath || 'images';

    // Check if filename already has timestamp pattern (e.g., 1772057218560-ef1e7dbd.jpg or long hex strings)
    const timestampPattern = /^\d{13}-[a-zA-Z0-9]{6,}/;
    if (timestampPattern.test(fileName)) {
      // Use filename as-is since it already has unique timestamp and random hex
      return `${prefix}${entityPath}/${fileName}`;
    }

    // Generate new timestamp and random ID for regular filenames
    const timestamp = Date.now();
    const randomId = Math.random().toString(36).substring(2, 10);

    const cleanFileName = fileName.replace(/[^a-zA-Z0-9.-]/g, '');
    const extension = this.getFileExtension(fileName);
    // Use a safer approach without RegExp constructor
    const extensionPattern = `.${extension}`;
    const baseName = cleanFileName.toLowerCase().endsWith(extensionPattern.toLowerCase())
      ? cleanFileName.slice(0, -extensionPattern.length)
      : cleanFileName;

    return `${prefix}${entityPath}/${timestamp}-${randomId}-${baseName}.${extension}`;
  }
}

module.exports = ServerImageOptimizationService;
